/**
 * Mock data service used during development / demo mode.
 *
 * When no real MCP connectors are configured (no API tokens) the app uses
 * this module to supply realistic sample data so every UI component can be
 * exercised without credentials.
 */

import type { RawEvent, RankedEvent } from "@/lib/types";

const now = new Date();
const ago = (minutes: number) =>
  new Date(now.getTime() - minutes * 60_000).toISOString();

export const mockRawEvents: RawEvent[] = [
  {
    id: "github-pr-1001",
    source: "github",
    title: "PR #42: Fix critical memory leak in WebSocket handler",
    body: "This PR addresses the memory leak identified in issue #38. The root cause was an unclosed event listener in the WebSocket connection teardown path.",
    url: "https://github.com/example/repo/pull/42",
    author: "alice",
    createdAt: ago(120),
    updatedAt: ago(15),
    metadata: { type: "pull_request", state: "open", number: 42 },
  },
  {
    id: "github-issue-2002",
    source: "github",
    title: "Issue #99: Production API returning 500 on /users endpoint",
    body: "After the latest deploy we are seeing intermittent 500 errors on the /users endpoint. Logs show a NullPointerException in UserService.",
    url: "https://github.com/example/repo/issues/99",
    author: "bob",
    createdAt: ago(240),
    updatedAt: ago(30),
    metadata: { type: "issue", number: 99 },
  },
  {
    id: "calendar-001",
    source: "google_calendar",
    title: "Sprint planning – Q2 roadmap review",
    body: "All hands sprint planning session. Bring your estimates for the next two sprints.",
    url: "https://calendar.google.com/event?eid=abc123",
    author: "Charlie (Organizer)",
    createdAt: ago(1440),
    updatedAt: ago(60),
    metadata: { type: "calendar_event", start: new Date(now.getTime() + 3600_000).toISOString() },
  },
  {
    id: "github-pr-1003",
    source: "github",
    title: "PR #55: Add dark-mode support to dashboard",
    body: "Implements the dark-mode theme toggling using CSS variables and the prefers-color-scheme media query.",
    url: "https://github.com/example/repo/pull/55",
    author: "diana",
    createdAt: ago(360),
    updatedAt: ago(90),
    metadata: { type: "pull_request", state: "open", number: 55 },
  },
  {
    id: "notion-page-3001",
    source: "notion",
    title: "Q2 Product Strategy Document – draft",
    body: "This document outlines the product strategy for Q2, including target markets, feature priorities, and success metrics.",
    url: "https://notion.so/q2-strategy",
    author: "Product Team",
    createdAt: ago(2880),
    updatedAt: ago(180),
    metadata: { type: "notion_page" },
  },
  {
    id: "github-issue-2005",
    source: "github",
    title: "Issue #110: CI pipeline failing on Node 20",
    body: "The GitHub Actions CI pipeline is failing with deprecation errors on Node 20. Needs dependency upgrades.",
    url: "https://github.com/example/repo/issues/110",
    author: "eve",
    createdAt: ago(480),
    updatedAt: ago(45),
    metadata: { type: "issue", number: 110 },
  },
  {
    id: "calendar-002",
    source: "google_calendar",
    title: "1:1 with Engineering Manager",
    body: "Regular weekly 1:1. Topics: OKR progress, blockers, career growth.",
    url: "https://calendar.google.com/event?eid=def456",
    author: "Manager (Organizer)",
    createdAt: ago(7200),
    updatedAt: ago(1440),
    metadata: { type: "calendar_event", start: new Date(now.getTime() + 86400_000).toISOString() },
  },
  {
    id: "github-pr-1006",
    source: "github",
    title: "PR #61: Refactor authentication middleware",
    body: "Modernises the auth middleware to use JWT RS256. Includes unit tests and migration guide.",
    url: "https://github.com/example/repo/pull/61",
    author: "frank",
    createdAt: ago(600),
    updatedAt: ago(200),
    metadata: { type: "pull_request", state: "open", number: 61 },
  },
  {
    id: "notion-page-3002",
    source: "notion",
    title: "On-call Runbook – Database failover procedure",
    body: "Step-by-step instructions for performing a manual database failover during an incident.",
    url: "https://notion.so/db-failover",
    author: "SRE Team",
    createdAt: ago(43200),
    updatedAt: ago(720),
    metadata: { type: "notion_page" },
  },
  {
    id: "github-issue-2007",
    source: "github",
    title: "Issue #77: Improve search index performance",
    body: "Full-text search queries are taking >2s on large datasets. We should evaluate Elasticsearch vs pg_trgm.",
    url: "https://github.com/example/repo/issues/77",
    author: "grace",
    createdAt: ago(2160),
    updatedAt: ago(300),
    metadata: { type: "issue", number: 77 },
  },
];

export const mockRankedEvents: RankedEvent[] = [
  {
    ...mockRawEvents[0],
    score: 9,
    summary: "Critical memory leak PR needs review — directly impacts production stability.",
    actionType: "review_pr",
    tags: ["critical", "bug", "performance"],
    category: "code_review",
    rankedAt: ago(5),
  },
  {
    ...mockRawEvents[1],
    score: 9,
    summary: "Production 500 errors on /users — immediate investigation required.",
    actionType: "fix_bug",
    tags: ["critical", "production", "api"],
    category: "issue",
    rankedAt: ago(5),
  },
  {
    ...mockRawEvents[2],
    score: 8,
    summary: "Sprint planning in 1h — prepare estimates and roadmap input.",
    actionType: "join_meeting",
    tags: ["meeting", "sprint", "planning"],
    category: "meeting",
    rankedAt: ago(5),
  },
  {
    ...mockRawEvents[3],
    score: 6,
    summary: "Dark-mode PR awaiting review — low risk, improves UX.",
    actionType: "review_pr",
    tags: ["ui", "feature"],
    category: "code_review",
    rankedAt: ago(5),
  },
  {
    ...mockRawEvents[4],
    score: 5,
    summary: "Q2 strategy draft ready for async reading and comments.",
    actionType: "read_document",
    tags: ["strategy", "product", "q2"],
    category: "document",
    rankedAt: ago(5),
  },
  {
    ...mockRawEvents[5],
    score: 7,
    summary: "CI pipeline broken on Node 20 — blocks merges until fixed.",
    actionType: "fix_bug",
    tags: ["ci", "devops", "blocking"],
    category: "issue",
    rankedAt: ago(5),
  },
  {
    ...mockRawEvents[6],
    score: 4,
    summary: "Weekly 1:1 tomorrow morning — optional prep recommended.",
    actionType: "join_meeting",
    tags: ["meeting", "1:1"],
    category: "meeting",
    rankedAt: ago(5),
  },
  {
    ...mockRawEvents[7],
    score: 5,
    summary: "Auth middleware PR modernises JWT handling — medium complexity review.",
    actionType: "review_pr",
    tags: ["security", "refactor"],
    category: "code_review",
    rankedAt: ago(5),
  },
  {
    ...mockRawEvents[8],
    score: 3,
    summary: "DB failover runbook updated — good reference for on-call rotation.",
    actionType: "read_document",
    tags: ["runbook", "sre"],
    category: "document",
    rankedAt: ago(5),
  },
  {
    ...mockRawEvents[9],
    score: 4,
    summary: "Search performance issue tracked — low urgency, worth researching.",
    actionType: "none",
    tags: ["performance", "search"],
    category: "issue",
    rankedAt: ago(5),
  },
];
